# Generated by Django 5.2.3 on 2025-07-14 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meszkanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_mieszkania', models.IntegerField(default=0)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miasto', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=500)),
                ('liczba_osob', models.IntegerField(default=1)),
                ('powierzchnia', models.IntegerField(default=1)),
                ('liczba_pokojow', models.IntegerField(default=1)),
                ('opis', models.CharField(max_length=500)),
                ('dostepnosc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_z', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_do', models.DateTimeField(default=django.utils.timezone.now)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REZERVACJA.klient')),
                ('meszkanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REZERVACJA.meszkanie')),
            ],
        ),
    ]
