# Generated by Django 5.2.3 on 2025-07-14 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVACJA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meszkanie',
            name='data_publikowania',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
