# Generated by Django 5.2.3 on 2025-07-14 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVACJA', '0002_meszkanie_data_publikowania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('opis', models.CharField(max_length=1000)),
                ('data_publikowania', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
