# Generated by Django 5.2.3 on 2025-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVACJA', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Nr_post',
            field=models.IntegerField(default=0),
        ),
    ]
