services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: interview123
      MYSQL_PASSWORD: interview123
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend_api
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

networks:
  backend:


volumes:
  db-vol:
